services:
  postgres:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    networks:
      - services

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - services

  api:
    build:
      context: ./
      dockerfile: cmd/Dockerfile
    deploy:
      replicas: 4
    env_file:
      - docker.env
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - services

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - services
    depends_on:
      - api

networks:
  services:
