services:
  postgres:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    networks:
      - services

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - services

  user-service:
    build:
      context: ./
      dockerfile: cmd/user_service/Dockerfile
    deploy:
      replicas: 2
    env_file:
      - user_service.env
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - services

  notifications-service:
    build:
      context: ./
      dockerfile: cmd/notifications_service/Dockerfile
    deploy:
      replicas: 2
    env_file:
      - notifications_service.env
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - services

  promotions-service:
    build:
      context: ./
      dockerfile: cmd/promotions_service/Dockerfile
    deploy:
      replicas: 2
    env_file:
      - promotions_service.env
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - services

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - services
    depends_on:
      - user-service
      - notifications-service
      - promotions-service

networks:
  services:
